# Config file for automatic testing at travis-ci.org

language: python

sudo: false

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=pypy

install: pip install -U tox

script: tox
